sudo: required
services:
  - docker

before_install:
  - docker build -t andvod/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true andvod/docker-frontend npm run test

after_success:
  - docker build -f Dockerfile.prod -t andvod/docker-frontend:0.3 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push andvod/docker-frontend:0.3

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-frontend"
  env: "docker-frontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-800384250910"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

after_deploy:
  - echo "deployed success"